FROM debian:bookworm

RUN apt update && apt upgrade -y && apt install -y wget p7zip* unzip \
    build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev \
    libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev \
    libxi-dev libxrandr-dev yasm